from enum import Enum

from biblemark.exceptions.bible_http_exceptions import InvalidBook
from biblemark.model.bible_book_info import BibleBookInfo


class BibleBook(Enum):
    GENESIS = BibleBookInfo("GEN", "Genesis")
    EXODUS = BibleBookInfo("EXO", "Exodus")
    LEVITICUS = BibleBookInfo("LEV", "Leviticus")
    NUMBERS = BibleBookInfo("NUM", "Numbers")
    DEUTERONOMY = BibleBookInfo("DEU", "Deuteronomy")
    JOSHUA = BibleBookInfo("JOS", "Joshua")
    JUDGES = BibleBookInfo("JDG", "Judges")
    RUTH = BibleBookInfo("RUT", "Ruth")
    FIRST_SAMUEL = BibleBookInfo("1SA", "1 Samuel")
    SECOND_SAMUEL = BibleBookInfo("2SA", "2 Samuel")
    FIRST_KINGS = BibleBookInfo("1KI", "1 Kings")
    SECOND_KINGS = BibleBookInfo("2KI", "2 Kings")
    FIRST_CHRONICLES = BibleBookInfo("1CH", "1 Chronicles")
    SECOND_CHRONICLES = BibleBookInfo("2CH", "2 Chronicles")
    EZRA = BibleBookInfo("EZR", "Ezra")
    NEHEMIAH = BibleBookInfo("NEH", "Nehemiah")
    ESTHER = BibleBookInfo("EST", "Esther (Hebrew)")
    JOB = BibleBookInfo("JOB", "Job")
    PSALMS = BibleBookInfo("PSA", "Psalms")
    PROVERBS = BibleBookInfo("PRO", "Proverbs")
    ECCLESIASTES = BibleBookInfo("ECC", "Ecclesiastes")
    SONG_OF_SONGS = BibleBookInfo("SNG", "Song of Songs")
    ISAIAH = BibleBookInfo("ISA", "Isaiah")
    JEREMIAH = BibleBookInfo("JER", "Jeremiah")
    LAMENTATIONS = BibleBookInfo("LAM", "Lamentations")
    EZEKIEL = BibleBookInfo("EZK", "Ezekiel")
    DANIEL = BibleBookInfo("DAN", "Daniel (Hebrew)")
    HOSEA = BibleBookInfo("HOS", "Hosea")
    JOEL = BibleBookInfo("JOL", "Joel")
    AMOS = BibleBookInfo("AMO", "Amos")
    OBADIAH = BibleBookInfo("OBA", "Obadiah")
    JONAH = BibleBookInfo("JON", "Jonah")
    MICAH = BibleBookInfo("MIC", "Micah")
    NAHUM = BibleBookInfo("NAM", "Nahum")
    HABAKKUK = BibleBookInfo("HAB", "Habakkuk")
    ZEPHANIAH = BibleBookInfo("ZEP", "Zephaniah")
    HAGGAI = BibleBookInfo("HAG", "Haggai")
    ZECHARIAH = BibleBookInfo("ZEC", "Zechariah")
    MALACHI = BibleBookInfo("MAL", "Malachi")

    MATTHEW = BibleBookInfo("MAT", "Matthew")
    MARK = BibleBookInfo("MRK", "Mark")
    LUKE = BibleBookInfo("LUK", "Luke")
    JOHN = BibleBookInfo("JHN", "John")
    ACTS = BibleBookInfo("ACT", "Acts")
    ROMANS = BibleBookInfo("ROM", "Romans")
    FIRST_CORINTHIANS = BibleBookInfo("1CO", "1 Corinthians")
    SECOND_CORINTHIANS = BibleBookInfo("2CO", "2 Corinthians")
    GALATIANS = BibleBookInfo("GAL", "Galatians")
    EPHESIANS = BibleBookInfo("EPH", "Ephesians")
    PHILIPPIANS = BibleBookInfo("PHP", "Philippians")
    COLOSSIANS = BibleBookInfo("COL", "Colossians")
    FIRST_THESSALONIANS = BibleBookInfo("1TH", "1 Thessalonians")
    SECOND_THESSALONIANS = BibleBookInfo("2TH", "2 Thessalonians")
    FIRST_TIMOTHY = BibleBookInfo("1TI", "1 Timothy")
    SECOND_TIMOTHY = BibleBookInfo("2TI", "2 Timothy")
    TITUS = BibleBookInfo("TIT", "Titus")
    PHILEMON = BibleBookInfo("PHM", "Philemon")
    HEBREWS = BibleBookInfo("HEB", "Hebrews")
    JAMES = BibleBookInfo("JAS", "James")
    FIRST_PETER = BibleBookInfo("1PE", "1 Peter")
    SECOND_PETER = BibleBookInfo("2PE", "2 Peter")
    FIRST_JOHN = BibleBookInfo("1JN", "1 John")
    SECOND_JOHN = BibleBookInfo("2JN", "2 John")
    THIRD_JOHN = BibleBookInfo("3JN", "3 John")
    JUDE = BibleBookInfo("JUD", "Jude")
    REVELATION = BibleBookInfo("REV", "Revelation")

    TOBIT = BibleBookInfo("TOB", "Tobit")
    JUDITH = BibleBookInfo("JDT", "Judith")
    ESTHER_GREEK = BibleBookInfo("ESG", "Esther Greek")
    WISDOM_OF_SOLOMON = BibleBookInfo("WIS", "Wisdom of Solomon")
    SIRACH = BibleBookInfo("SIR", "Sirach")
    BARUCH = BibleBookInfo("BAR", "Baruch")
    LETTER_OF_JEREMIAH = BibleBookInfo("LJE", "Letter of Jeremiah")
    SONG_OF_THE_3_YOUNG_MEN = BibleBookInfo("S3Y", "Song of the 3 Young Men")
    SUSANNA = BibleBookInfo("SUS", "Susanna")
    BEL_AND_THE_DRAGON = BibleBookInfo("BEL", "Bel and the Dragon")
    FIRST_MACCABEES = BibleBookInfo("1MA", "1 Maccabees")
    SECOND_MACCABEES = BibleBookInfo("2MA", "2 Maccabees")
    THIRD_MACCABEES = BibleBookInfo("3MA", "3 Maccabees")
    FOURTH_MACCABEES = BibleBookInfo("4MA", "4 Maccabees")
    FIRST_ESDRAS = BibleBookInfo("1ES", "1 Esdras (Greek)")
    SECOND_ESDRAS = BibleBookInfo("2ES", "2 Esdras (Latin)")
    PRAYER_OF_MANASSEH = BibleBookInfo("MAN", "Prayer of Manasseh")
    PSALM_151 = BibleBookInfo("PS2", "Psalm 151")
    ODES = BibleBookInfo("ODA", "Odae/Odes")
    PSALMS_OF_SOLOMON = BibleBookInfo("PSS", "Psalms of Solomon")
    EZRA_APOCALYPSE = BibleBookInfo("EZA", "Ezra Apocalypse")
    FIFTH_EZRA = BibleBookInfo("5EZ", "5 Ezra")
    SIXTH_EZRA = BibleBookInfo("6EZ", "6 Ezra")
    DANIEL_GREEK = BibleBookInfo("DAG", "Daniel Greek")
    PSALMS_152_155 = BibleBookInfo("PS3", "Psalms 152-155")
    SECOND_BARUCH = BibleBookInfo("2BA", "2 Baruch (Apocalypse)")
    LETTER_OF_BARUCH = BibleBookInfo("LBA", "Letter of Baruch")
    JUBILEES = BibleBookInfo("JUB", "Jubilees")
    ENOCH = BibleBookInfo("ENO", "Enoch")
    FIRST_MEQABYAN = BibleBookInfo("1MQ", "1 Meqabyan/Mekabis")
    SECOND_MEQABYAN = BibleBookInfo("2MQ", "2 Meqabyan/Mekabis")
    THIRD_MEQABYAN = BibleBookInfo("3MQ", "3 Meqabyan/Mekabis")
    REPROOF = BibleBookInfo("REP", "Reproof")
    FOURTH_BARUCH = BibleBookInfo("4BA", "4 Baruch")
    LETTER_TO_THE_LAODICEANS = BibleBookInfo("LAO", "Letter to the Laodiceans")
    FRONT_MATTER = BibleBookInfo("FRT", "Front Matter")
    BACK_MATTER = BibleBookInfo("BAK", "Back Matter")
    OTHER_MATTER = BibleBookInfo("OTH", "Other Matter")
    INTRODUCTION_MATTER = BibleBookInfo("INT", "Introduction Matter")
    CONCORDANCE = BibleBookInfo("CNC", "Concordance")
    GLOSSARY = BibleBookInfo("GLO", "Glossary / Wordlist")
    TOPICAL_INDEX = BibleBookInfo("TDX", "Topical Index")
    NAMES_INDEX = BibleBookInfo("NDX", "Names Index")
    EXTRA_MATERIAL_A = BibleBookInfo("XXA", "Extra material")
    EXTRA_MATERIAL_B = BibleBookInfo("XXB", "Extra material")
    EXTRA_MATERIAL_C = BibleBookInfo("XXC", "Extra material")
    EXTRA_MATERIAL_D = BibleBookInfo("XXD", "Extra material")
    EXTRA_MATERIAL_E = BibleBookInfo("XXE", "Extra material")
    EXTRA_MATERIAL_F = BibleBookInfo("XXF", "Extra material")
    EXTRA_MATERIAL_G = BibleBookInfo("XXG", "Extra material")

    def get_id(self):
        return self.value.id


def parse_book(book_id: str) -> BibleBook:
    for member in BibleBook:
        if member.value.id == book_id:
            return member
    raise InvalidBook(f"Book {book_id} is not supported")
